{% set name = "tad-dftd4" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tad_dftd4-{{ version }}.tar.gz
  sha256: 7267824b766f86d3b8c05f17361684a8e8bc918de9b09c9159255061b61303b1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - pip
  run:
    - python >=3.8
    - numpy
    - tad-mctc
    - tad-multicharge
    - pytorch >=1.11

test:
  imports:
    - tad_dftd4
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Torch autodiff DFT-D4 implementation
  home: https://github.com/dftd4/tad-dftd4
  dev_url: https://github.com/dftd4/tad-dftd4
  doc_url: https://tad-dftd4.readthedocs.io/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marvinfriede
